[package]
name = "fox-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
fox-core = { path = "../fox-core" }
serde = { workspace = true }
serde_json = { workspace = true }
fox-secret = { path = "../fox-secret" }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
sqlx = { workspace = true }
dirs = { workspace = true }