[package]
name = "fox-oauth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
fox-core = { path = "../fox-core" }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
axum = { workspace = true }
webbrowser = { workspace = true }